# Generated by Django 5.2.17 on 2026-09-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_emergency_contact_employee_emergency_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='employee_photos/'),
        ),
    ]
